### ISSUE TITLE
FOSS Kickstart substitute?

### ISSUE THREAD

**Issue by danboid** [nicodex/HelloAmi#10]
This sounds like an interesting project but I'm not 100% sure on what it does.

Is it fair to say this is an open source, clean-room reimplementation of the Amigas kickstart rom? If thats what is has grown into, why do you not say this in the README? Maybe thats intentional for legal reasons?

If thats what HelloAmi is, more or less, what features does it lack that genuine kickstart roms have, if any? I'd like to see this info added to the README.

Thanks

**Comment by nicodex** [comment]
> Is it fair to say this is an open source, clean-room reimplementation of the Amigas kickstart rom?

It is not a re-implementation of the Kickstart/AmigaOS, and never will be.
You might be looking for the https://en.wikipedia.org/wiki/AROS_Research_Operating_System

In this project I tried to get used to the AmigaOS and wanted to create a floppy disk that boots into the graphical user interface. But the 1.x Kickstart ROMs do not include the icon.library - so I did a clean implementation of this library to close this little gap. With this library you can boot into the 1.x Workbench that is included in the Kickstart ROM - but note that you boot into a very basic system and most of the tools that make up the AmigaOS are missing. So this environment is very limited, but it might be useful to initially setup a system or to start some tools.
